### ISSUE TITLE
MSE object is enormous for SWO with 289 simulations!

### ISSUE THREAD

**Issue by AdrianHordyk** [Blue-Matter/MSEtool#18]
May need to modify MSE object to reduce the size

**Comment by AdrianHordyk** [comment]
remove Misc$Data - that will help a bit

**Comment by AdrianHordyk** [comment]
also option to remove Hist?

**Comment by quang-huynh** [comment]
There's redundancy because the Hist is reported twice in `MSE@Hist` as well as in `MSE@PPD$Data[[1]]@Misc`. Could do a quick post-hoc removal in @Misc (although I need the info in `Data@Misc[1:nsim]` for model-based MPs).

Could also create a new argument e.g.  `runMSE(report = c("min", "full"))` to return a smaller vs full MSE object.

**Comment by AdrianHordyk** [comment]
Ah good point redundancy with `StockPars` etc in `PPD@Misc`.  I'll drop those out before returning the `MSE` object. 

Also, for backwards compatibility I had PPD in `MSE@PPD` and `MSE@Misc$Data` but going to drop the latter now.

I have an argument `extended` to `runMSE` which returns N, biomass, etc, by simulation, age, MP, year and area in `MSE@Misc$extended`. Can add other optional output there as well.
